### ISSUE TITLE
transitionend event

### ISSUE THREAD

**Issue by ajaytdev** [WebAnimationWorkshops/ama#1]
hey i was transforming the scale of a box on keypress(keydown event). and i wanted to count how many times i am pressing the key . 
`var count = 0;
		function playSound(e){
			
			const key= document.querySelector(`div[data-key='${e.keyCode}']`);
			const audio = document.querySelector(`audio[data-key='${e.keyCode}']`);
	
			if(!audio) return; 					// if there is no audio element
			count+=1;
			key.classList.add('playing');
			audio.currentTime=0;
			audio.play(); 
			

			function transitionEnd(e){
				if(e.propertyName!='transform') return;
                                console.log(count);
				this.classList.remove('playing');
			}
			
			key.addEventListener('transitionend',transitionEnd);
			
		};

		window.addEventListener('keydown',playSound);`
so when i pressed keys and everytime on key press the count was printed two times on a single press of accepted keys. for eg:
(2)1
(2)2
(2)3.
this is the output of devtools . what could be the reason for two times printing.

**Comment by valhead** [comment]
Hi Ajay! 
Thanks for posting a question. 

We took a look at your code in CodePen and, based on the snippet you posted,  the count is likely printing twice because you're logging it twice before the count changes. 

It's called once in the playSound function right after the transition is called (we assumed that assigning the 'playing' class is what triggered your transition) then logged again after the transition is over. If count hasn't changed in that amount of time, both those console.log()s would report the same total for count. Totally a common thing to do! If you take out one of those calls, you should get the results you're looking for.

**Comment by ajaytdev** [comment]
@valhead sorry for typo . console.log(count); after audio is commented out . i forgot to do that. i updated the code.  console.log(count); in function transitionEnd(e) is causing printing twice . here i am attaching a screenshot.
![count](https://cloud.githubusercontent.com/assets/12777204/21997059/30933864-dc53-11e6-913b-7404d892c083.png)

**Comment by sdras** [comment]
Hi Ajay!

So, I'm pretty sure what's happening is you are also removing the classlist for playing, which is triggering another transition on the way out (you have a default transition on the div itself, so it will use that when the state of the div returns to its defaults). If you comment out the line where you remove the class of 'playing', it only counts once.

Another small note: it might be better to use another name for the transitionEnd function, as it's pretty close to a reserved word (though that's a stylistic preference!). 

I hope that's helpful!

**Comment by ajaytdev** [comment]
Thank you so much @sdras . Great explanation, kudos.if you don't mind ,now onwards i will tweet you if some problem arises. Thanks :) :+1:

**Comment by sdras** [comment]
awesome!
